---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Icecast2
  apt:
    name: icecast2
    state: present

- name: Ensure icecast group exists
  group:
    name: "{{ icecast_group }}"
    state: present

- name: Ensure icecast user exists
  user:
    name: "{{ icecast_user }}"
    group: "{{ icecast_group }}"
    system: yes
    shell: /usr/sbin/nologin
    create_home: no

- name: Configure Icecast2
  template:
    src: icecast.xml.j2
    dest: "{{ icecast_config_file }}"
    owner: "{{ icecast_user }}"
    group: "{{ icecast_group }}"
    mode: '0644'
  notify:
    - reload Icecast

- name: Enable and start Icecast2
  systemd:
    name: icecast2
    enabled: yes
    state: started

- name: Open port 8000 for Icecast traffic
  ansible.builtin.ufw:
    rule: allow
    port: 8000
    proto: tcp