- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx for Icecast
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default

- name: Replace default Nginx index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0755'
    owner: 'www-data'
    group: 'www-data'

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes

- name: All all Nginx traffic thorugh UFW
  ufw:
    rule: allow
    name: 'Nginx Full'

- name: Reload UFW
  ufw:
    state: reloaded
