- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx for Icecast
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: reload nginx

- name: Enable Nginx site
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload nginx

- name: Replace default Nginx index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    mode: '0755'
    owner: 'www-data'
    group: 'www-data'

- name: Ensure Nginx is running
  service:
    name: nginx
    state: started
    enabled: yes